dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank


jobs:
  include:
    - stage: build and publish
      language: java
      jdk: oraclejdk8
      install: skip
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Krishnaw"
        - git config --local user.email "krishna.wudaru@gmail.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: cbe9477bebf63bbe5a9a3a46dab55d86e253b9d8
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
    - stage: deploy to review
      language: bash
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/pal-tracker/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to review"
      deploy:
        provider: cloudfoundry
        api: https://api.sys.evans.pal.pivotal.io
        username: krishna.wudaru@albertsons.com
        password: hnremct3
        organization: krishna-wudaru
        space: review
